class_name: runs.play.PlayRun
num_trials: 5
seed: 12
players:
  - name: player_1
    implementation: client
  - name: player_2
    implementation: actors.overcooked_bc.SimpleBCActor
    agent_config: #starting checkpoint of training
      model_id: gracious_ishizaka_0_model
